# Generated by Django 4.2 on 2025-04-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('cricket', 'Cricket'), ('rugby', 'Rugby'), ('hockey', 'Hockey'), ('volleyball', 'Volleyball'), ('baseball', 'Baseball'), ('american_football', 'American Football'), ('boxing', 'Boxing'), ('mixed_martial_arts', 'Mixed Martial Arts')], default='football', max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='leagues/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('cricket', 'Cricket'), ('rugby', 'Rugby'), ('hockey', 'Hockey'), ('volleyball', 'Volleyball'), ('baseball', 'Baseball'), ('american_football', 'American Football'), ('boxing', 'Boxing'), ('mixed_martial_arts', 'Mixed Martial Arts')], default='football', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.league')),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('cricket', 'Cricket'), ('rugby', 'Rugby'), ('hockey', 'Hockey'), ('volleyball', 'Volleyball'), ('baseball', 'Baseball'), ('american_football', 'American Football'), ('boxing', 'Boxing'), ('mixed_martial_arts', 'Mixed Martial Arts')], default='football', max_length=100)),
                ('home_team_score', models.IntegerField(blank=True, default=0, null=True)),
                ('away_team_score', models.IntegerField(blank=True, default=0, null=True)),
                ('match_date', models.DateTimeField()),
                ('match_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='core.team')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.league')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
