# Generated by Django 4.2 on 2025-04-26 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('cricket', 'Cricket'), ('rugby', 'Rugby'), ('hockey', 'Hockey'), ('volleyball', 'Volleyball'), ('baseball', 'Baseball'), ('american_football', 'American Football'), ('boxing', 'Boxing'), ('mixed_martial_arts', 'Mixed Martial Arts')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('market_key', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Market Types',
                'unique_together': {('sport', 'market_key')},
            },
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_value', models.FloatField()),
                ('odds_type', models.CharField(choices=[('decimal', 'Decimal'), ('fractional', 'Fractional'), ('moneyline', 'Moneyline')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='betting.markettype')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='core.match')),
            ],
            options={
                'verbose_name_plural': 'Odds',
                'unique_together': {('market_type', 'match')},
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.FloatField()),
                ('potential_return', models.FloatField()),
                ('bet_status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betting.markettype')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='core.match')),
                ('odds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betting.odds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bets',
                'ordering': ['-created_at'],
            },
        ),
    ]
